extends Node

enum TransitionType {
	TRANS_LINEAR = Tween.TRANS_LINEAR,
	TRANS_SINE = Tween.TRANS_SINE,
	TRANS_QUINT = Tween.TRANS_QUINT,
	TRANS_QUART = Tween.TRANS_QUART,
	TRANS_QUAD = Tween.TRANS_QUAD,
	TRANS_EXPO = Tween.TRANS_EXPO,
	TRANS_ELASTIC = Tween.TRANS_ELASTIC,
	TRANS_CUBIC = Tween.TRANS_CUBIC,
	TRANS_CIRC = Tween.TRANS_CIRC,
	TRANS_BOUNCE = Tween.TRANS_BOUNCE
	TRANS_BACK = Tween.TRANS_BACK
}

enum Easing {
	EASE_IN = Tween.EASE_IN
	EASE_OUT = Tween.EASE_OUT
	EASE_IN_OUT = Tween.EASE_IN_OUT
	EASE_OUT_IN = Tween.EASE_OUT_IN
}
